contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://dceoy.github.io/blog/"
title = "Lorem Ipsum"
canonifyurls = true
copyright = "Copyright (c) 2015 dceoy; all rights reserved."

[indexes]
  category = "categories"
  tag = "tags"

[params]
  description = "Interdisciplinary Science"
  highlight = "atelier-lakeside.light"

[author]
  name = "dceoy"
  github = "dceoy"
  twitter = "dceoy"
  gaID = "UA-27914660-5"
