contentdir = 'content'
layoutdir = 'layouts'
publishdir = 'public'
baseurl = 'https://dceoy.github.io/blog/'
title = 'Lorem Ipsum'
canonifyurls = true
copyright = 'Copyright (c) 2015-2018 dceoy; all rights reserved.'

[indexes]
  category = 'categories'
  tag = 'tags'

[params]
  highlight = 'github'
  topmenu = 'categories'

[author]
  name = 'dceoy'
  github = 'dceoy'
  twitter = 'dceoy'
  facebook = 'daichi.narushima'
  linkedin = 'daichi-narushima-65676641'
  gaid = 'UA-27914660-5'
